[2024-03-19T07:11:47.418+0000] {processor.py:153} INFO - Started process (PID=40) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:11:47.419+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:11:47.420+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:11:47.420+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:11:47.538+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:11:47.536+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:11:47.538+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:11:47.552+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.137 seconds
[2024-03-19T07:12:17.667+0000] {processor.py:153} INFO - Started process (PID=95) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:12:17.668+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:12:17.669+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:12:17.669+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:12:17.769+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:12:17.764+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:12:17.770+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:12:17.807+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.146 seconds
[2024-03-19T07:12:47.973+0000] {processor.py:153} INFO - Started process (PID=140) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:12:47.974+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:12:47.974+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:12:47.974+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:12:48.016+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:12:48.014+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:12:48.016+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:12:48.032+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.061 seconds
[2024-03-19T07:13:18.264+0000] {processor.py:153} INFO - Started process (PID=185) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:13:18.265+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:13:18.267+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:13:18.267+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:13:18.368+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:13:18.362+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:13:18.369+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:13:18.413+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.155 seconds
[2024-03-19T07:13:48.503+0000] {processor.py:153} INFO - Started process (PID=239) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:13:48.504+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:13:48.506+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:13:48.506+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:13:48.604+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:13:48.599+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:13:48.605+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:13:48.646+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.148 seconds
[2024-03-19T07:14:18.855+0000] {processor.py:153} INFO - Started process (PID=276) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:14:18.855+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:14:18.856+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:14:18.856+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:14:18.895+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:14:18.893+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:14:18.896+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:14:18.911+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.058 seconds
[2024-03-19T07:14:49.111+0000] {processor.py:153} INFO - Started process (PID=330) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:14:49.113+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:14:49.114+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:14:49.114+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:14:49.264+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:14:49.256+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:14:49.266+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:14:49.321+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.217 seconds
[2024-03-19T07:15:19.525+0000] {processor.py:153} INFO - Started process (PID=385) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:15:19.525+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:15:19.526+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:15:19.526+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:15:19.567+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:15:19.564+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:15:19.567+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:15:19.590+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.068 seconds
[2024-03-19T07:15:49.772+0000] {processor.py:153} INFO - Started process (PID=422) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:15:49.774+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:15:49.776+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:15:49.775+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:15:49.871+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:15:49.866+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:15:49.873+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:15:49.911+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.145 seconds
[2024-03-19T07:16:20.014+0000] {processor.py:153} INFO - Started process (PID=477) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:16:20.016+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:16:20.017+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:16:20.017+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:16:20.116+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:16:20.109+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:16:20.117+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:16:20.160+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.151 seconds
[2024-03-19T07:16:50.384+0000] {processor.py:153} INFO - Started process (PID=514) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:16:50.385+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:16:50.385+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:16:50.385+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:16:50.452+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:16:50.449+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:16:50.453+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:16:50.470+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.089 seconds
[2024-03-19T07:17:20.620+0000] {processor.py:153} INFO - Started process (PID=569) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:17:20.623+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:17:20.626+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:17:20.625+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:17:20.799+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:17:20.796+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:17:20.799+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:17:20.827+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.217 seconds
[2024-03-19T07:18:28.598+0000] {processor.py:153} INFO - Started process (PID=40) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:18:28.599+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:18:28.599+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:18:28.599+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:18:28.696+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:18:28.694+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:18:28.696+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:18:28.711+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.116 seconds
[2024-03-19T07:18:58.845+0000] {processor.py:153} INFO - Started process (PID=94) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:18:58.847+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:18:58.848+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:18:58.848+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:18:58.968+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:18:58.963+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:18:58.969+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:18:59.000+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.161 seconds
[2024-03-19T07:19:29.140+0000] {processor.py:153} INFO - Started process (PID=131) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:19:29.142+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:19:29.144+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:19:29.143+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:19:29.226+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:19:29.224+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:19:29.227+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:19:29.243+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.110 seconds
[2024-03-19T07:19:59.435+0000] {processor.py:153} INFO - Started process (PID=186) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:19:59.436+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:19:59.438+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:19:59.437+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:19:59.552+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:19:59.546+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:19:59.554+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:19:59.594+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.165 seconds
[2024-03-19T07:20:29.664+0000] {processor.py:153} INFO - Started process (PID=241) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:20:29.664+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:20:29.665+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:20:29.665+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:20:29.742+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:20:29.738+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:20:29.744+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:20:29.783+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.121 seconds
[2024-03-19T07:21:00.021+0000] {processor.py:153} INFO - Started process (PID=278) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:21:00.022+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:21:00.024+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:21:00.024+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:21:00.118+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:21:00.113+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:21:00.120+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:21:00.160+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.145 seconds
[2024-03-19T07:21:30.245+0000] {processor.py:153} INFO - Started process (PID=333) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:21:30.247+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:21:30.248+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:21:30.248+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:21:30.365+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:21:30.360+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:21:30.365+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:21:30.404+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.165 seconds
[2024-03-19T07:22:00.603+0000] {processor.py:153} INFO - Started process (PID=369) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:22:00.605+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:22:00.606+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:22:00.606+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:22:00.711+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:22:00.706+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:22:00.713+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:22:00.745+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.147 seconds
[2024-03-19T07:22:30.824+0000] {processor.py:153} INFO - Started process (PID=424) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:22:30.825+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:22:30.826+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:22:30.826+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:22:30.941+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:22:30.937+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:22:30.942+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:22:30.973+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.155 seconds
[2024-03-19T07:23:01.162+0000] {processor.py:153} INFO - Started process (PID=479) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:23:01.163+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:23:01.165+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:23:01.164+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:23:01.263+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:23:01.258+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:23:01.265+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:23:01.302+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.146 seconds
[2024-03-19T07:23:31.442+0000] {processor.py:153} INFO - Started process (PID=516) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:23:31.444+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:23:31.445+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:23:31.444+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:23:31.542+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:23:31.538+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:23:31.543+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:23:31.585+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.148 seconds
[2024-03-19T07:24:01.749+0000] {processor.py:153} INFO - Started process (PID=571) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:24:01.750+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:24:01.752+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:24:01.751+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:24:01.853+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:24:01.850+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:24:01.854+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:24:01.896+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.153 seconds
[2024-03-19T07:24:32.018+0000] {processor.py:153} INFO - Started process (PID=614) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:24:32.019+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:24:32.019+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:24:32.019+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:24:32.068+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:24:32.067+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:24:32.069+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:24:32.092+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.076 seconds
[2024-03-19T07:25:02.307+0000] {processor.py:153} INFO - Started process (PID=662) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:25:02.309+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:25:02.310+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:25:02.310+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:25:02.409+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:25:02.404+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:25:02.410+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:25:02.451+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.151 seconds
[2024-03-19T07:25:32.518+0000] {processor.py:153} INFO - Started process (PID=717) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:25:32.520+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:25:32.524+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:25:32.523+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:25:32.738+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:25:32.732+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:25:32.739+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:25:32.782+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.270 seconds
[2024-03-19T07:26:02.910+0000] {processor.py:153} INFO - Started process (PID=753) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:26:02.911+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:26:02.913+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:26:02.913+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:26:03.035+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:26:03.030+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:26:03.036+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:26:03.073+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.170 seconds
[2024-03-19T07:26:33.217+0000] {processor.py:153} INFO - Started process (PID=808) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:26:33.218+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:26:33.219+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:26:33.219+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:26:33.329+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:26:33.324+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:26:33.330+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:26:33.370+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.159 seconds
[2024-03-19T07:27:03.492+0000] {processor.py:153} INFO - Started process (PID=845) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:27:03.494+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:27:03.497+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:27:03.496+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:27:03.641+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:27:03.635+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:27:03.643+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:27:03.687+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.202 seconds
[2024-03-19T07:27:33.790+0000] {processor.py:153} INFO - Started process (PID=900) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:27:33.791+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:27:33.791+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:27:33.791+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:27:33.838+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:27:33.833+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:27:33.839+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:27:33.865+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.078 seconds
[2024-03-19T07:28:04.004+0000] {processor.py:153} INFO - Started process (PID=955) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:28:04.004+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:28:04.005+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:28:04.005+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:28:04.043+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:28:04.042+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:28:04.044+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:28:04.060+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.059 seconds
[2024-03-19T07:28:34.279+0000] {processor.py:153} INFO - Started process (PID=992) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:28:34.280+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:28:34.282+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:28:34.282+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:28:34.378+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:28:34.372+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:28:34.379+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:28:34.424+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.150 seconds
[2024-03-19T07:29:04.498+0000] {processor.py:153} INFO - Started process (PID=1047) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:29:04.499+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:29:04.501+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:29:04.500+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:29:04.634+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:29:04.631+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:29:04.635+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:29:04.676+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.184 seconds
[2024-03-19T07:29:34.853+0000] {processor.py:153} INFO - Started process (PID=1084) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:29:34.854+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:29:34.856+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:29:34.855+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:29:34.976+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:29:34.970+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:29:34.977+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:29:35.016+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.168 seconds
[2024-03-19T07:30:05.091+0000] {processor.py:153} INFO - Started process (PID=1139) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:30:05.091+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:30:05.092+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:30:05.091+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:30:05.153+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:30:05.149+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:30:05.153+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:30:05.182+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.094 seconds
[2024-03-19T07:30:35.323+0000] {processor.py:153} INFO - Started process (PID=1194) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:30:35.324+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:30:35.324+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:30:35.324+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:30:35.365+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:30:35.363+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:30:35.365+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:30:35.390+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.069 seconds
[2024-03-19T07:31:05.548+0000] {processor.py:153} INFO - Started process (PID=1231) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:31:05.550+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:31:05.551+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:31:05.551+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:31:05.654+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:31:05.648+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:31:05.655+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:31:05.702+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.158 seconds
[2024-03-19T07:31:35.786+0000] {processor.py:153} INFO - Started process (PID=1285) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:31:35.787+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:31:35.787+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:31:35.787+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:31:35.848+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:31:35.846+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:31:35.849+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:31:35.876+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.093 seconds
[2024-03-19T07:32:06.024+0000] {processor.py:153} INFO - Started process (PID=1322) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:32:06.026+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:32:06.027+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:32:06.027+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:32:06.146+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:32:06.141+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:32:06.147+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:32:06.190+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.173 seconds
[2024-03-19T07:32:36.307+0000] {processor.py:153} INFO - Started process (PID=1377) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:32:36.308+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:32:36.310+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:32:36.309+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:32:36.408+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:32:36.403+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:32:36.409+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:32:36.448+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.146 seconds
[2024-03-19T07:33:06.620+0000] {processor.py:153} INFO - Started process (PID=1432) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:33:06.621+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:33:06.621+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:33:06.621+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:33:06.661+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:33:06.659+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:33:06.662+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:33:06.684+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.066 seconds
[2024-03-19T07:33:36.909+0000] {processor.py:153} INFO - Started process (PID=1468) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:33:36.910+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:33:36.912+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:33:36.911+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:33:37.039+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:33:37.033+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:33:37.040+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:33:37.082+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.179 seconds
[2024-03-19T07:34:07.126+0000] {processor.py:153} INFO - Started process (PID=1523) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:34:07.127+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:34:07.128+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:34:07.128+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:34:07.189+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:34:07.186+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:34:07.190+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:34:07.208+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.085 seconds
[2024-03-19T07:34:37.357+0000] {processor.py:153} INFO - Started process (PID=1560) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:34:37.358+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:34:37.359+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:34:37.359+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:34:37.462+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:34:37.457+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:34:37.464+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:34:37.493+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.141 seconds
[2024-03-19T07:35:07.619+0000] {processor.py:153} INFO - Started process (PID=1614) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:35:07.621+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:35:07.622+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:35:07.622+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:35:07.722+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:35:07.719+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:35:07.723+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:35:07.764+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.151 seconds
[2024-03-19T07:35:37.933+0000] {processor.py:153} INFO - Started process (PID=1651) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:35:37.934+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:35:37.935+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:35:37.935+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:35:38.063+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:35:38.057+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:35:38.065+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:35:38.105+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.178 seconds
[2024-03-19T07:36:08.227+0000] {processor.py:153} INFO - Started process (PID=1706) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:36:08.228+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:36:08.230+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:36:08.229+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:36:08.360+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:36:08.353+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:36:08.361+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:36:08.404+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.184 seconds
[2024-03-19T07:36:38.547+0000] {processor.py:153} INFO - Started process (PID=1761) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:36:38.547+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:36:38.548+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:36:38.548+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:36:38.591+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:36:38.589+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:36:38.592+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:36:38.617+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.073 seconds
[2024-03-19T07:37:08.832+0000] {processor.py:153} INFO - Started process (PID=1797) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:37:08.833+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:37:08.835+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:37:08.834+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:37:08.940+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:37:08.934+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:37:08.941+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:37:08.985+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.159 seconds
[2024-03-19T07:37:39.031+0000] {processor.py:153} INFO - Started process (PID=1852) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:37:39.032+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:37:39.034+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:37:39.034+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:37:39.158+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:37:39.154+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:37:39.159+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:37:39.192+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.167 seconds
[2024-03-19T07:38:09.376+0000] {processor.py:153} INFO - Started process (PID=1889) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:38:09.377+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:38:09.377+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:38:09.377+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:38:09.419+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:38:09.417+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:38:09.419+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:38:09.432+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.057 seconds
[2024-03-19T07:38:39.609+0000] {processor.py:153} INFO - Started process (PID=1943) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:38:39.611+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:38:39.612+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:38:39.612+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:38:39.722+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:38:39.716+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:38:39.724+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:38:39.770+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.167 seconds
[2024-03-19T07:39:09.830+0000] {processor.py:153} INFO - Started process (PID=1986) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:39:09.830+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:39:09.831+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:39:09.831+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:39:09.871+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:39:09.869+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:39:09.871+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:39:09.897+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.069 seconds
[2024-03-19T07:39:40.067+0000] {processor.py:153} INFO - Started process (PID=2033) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:39:40.069+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:39:40.070+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:39:40.070+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:39:40.196+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:39:40.192+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:39:40.197+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:39:40.241+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.180 seconds
[2024-03-19T07:40:10.298+0000] {processor.py:153} INFO - Started process (PID=2088) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:40:10.300+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:40:10.302+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:40:10.302+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:40:10.432+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:40:10.430+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:40:10.433+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:40:10.458+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.168 seconds
[2024-03-19T07:40:40.664+0000] {processor.py:153} INFO - Started process (PID=2124) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:40:40.666+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:40:40.668+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:40:40.668+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:40:40.760+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:40:40.757+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:40:40.761+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:40:40.790+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.132 seconds
[2024-03-19T07:41:10.887+0000] {processor.py:153} INFO - Started process (PID=2178) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:41:10.888+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:41:10.890+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:41:10.890+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:41:10.991+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:41:10.987+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:41:10.992+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:41:11.034+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.155 seconds
[2024-03-19T07:41:41.189+0000] {processor.py:153} INFO - Started process (PID=2215) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:41:41.190+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:41:41.191+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:41:41.191+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:41:41.286+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:41:41.279+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:41:41.287+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:41:41.330+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.148 seconds
[2024-03-19T07:42:11.427+0000] {processor.py:153} INFO - Started process (PID=2269) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:42:11.428+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:42:11.429+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:42:11.428+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:42:11.489+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:42:11.487+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:42:11.490+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:42:11.518+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.094 seconds
[2024-03-19T07:42:41.663+0000] {processor.py:153} INFO - Started process (PID=2323) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:42:41.665+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:42:41.666+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:42:41.666+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:42:41.787+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:42:41.783+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:42:41.788+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:42:41.822+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.166 seconds
[2024-03-19T07:43:11.933+0000] {processor.py:153} INFO - Started process (PID=2360) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:43:11.934+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:43:11.935+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:43:11.935+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:43:12.065+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:43:12.059+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:43:12.067+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:43:12.100+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.173 seconds
[2024-03-19T07:43:42.247+0000] {processor.py:153} INFO - Started process (PID=2415) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:43:42.248+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:43:42.250+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:43:42.250+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:43:42.356+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:43:42.352+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:43:42.357+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:43:42.385+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.143 seconds
[2024-03-19T07:44:12.496+0000] {processor.py:153} INFO - Started process (PID=2452) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:44:12.497+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:44:12.499+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:44:12.499+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:44:12.597+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:44:12.592+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:44:12.598+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:44:12.643+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.152 seconds
[2024-03-19T07:44:42.786+0000] {processor.py:153} INFO - Started process (PID=2507) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:44:42.787+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:44:42.788+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:44:42.787+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:44:42.827+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:44:42.825+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:44:42.828+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:44:42.843+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.060 seconds
[2024-03-19T07:45:13.052+0000] {processor.py:153} INFO - Started process (PID=2562) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:45:13.054+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:45:13.056+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:45:13.056+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:45:13.190+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:45:13.185+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 10, in <module>
    from src.Convert_json_csv import process_files
  File "/opt/airflow/src/Convert_json_csv.py", line 14, in <module>
    gcs_client = storage.Client.from_service_account_json(json_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mlops-project-417704-47dfa275f621.json'
[2024-03-19T07:45:13.192+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:45:13.237+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.191 seconds
[2024-03-19T07:45:43.272+0000] {processor.py:153} INFO - Started process (PID=2599) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:45:43.273+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:45:43.274+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:45:43.274+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:45:43.427+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:45:43.427+0000] {Convert_json_csv.py:42} INFO - Starting process in directory: /opt/airflow/data
[2024-03-19T07:45:43.427+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:45:43.427+0000] {Convert_json_csv.py:45} ERROR - Directory does not exist: /opt/airflow/data
[2024-03-19T07:45:44.307+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:45:44.303+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 13, in <module>
    from src.Merge_Files import merge_files
  File "/opt/airflow/src/Merge_Files.py", line 53, in <module>
    merge_files()
  File "/opt/airflow/src/Merge_Files.py", line 14, in merge_files
    storage_client = storage.Client()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/client.py", line 171, in __init__
    _http=_http,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 320, in __init__
    _ClientProjectMixin.__init__(self, project=project, credentials=credentials)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 268, in __init__
    project = self._determine_default(project)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 287, in _determine_default
    return _determine_default_project(project)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_helpers/__init__.py", line 152, in _determine_default_project
    _, project = google.auth.default()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/auth/_default.py", line 620, in default
    credentials, project_id = checker()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/auth/_default.py", line 613, in <lambda>
    lambda: _get_explicit_environ_credentials(quota_project_id=quota_project_id),
  File "/home/airflow/.local/lib/python3.7/site-packages/google/auth/_default.py", line 234, in _get_explicit_environ_credentials
    os.environ[environment_vars.CREDENTIALS], quota_project_id=quota_project_id
  File "/home/airflow/.local/lib/python3.7/site-packages/google/auth/_default.py", line 122, in load_credentials_from_file
    "File {} was not found.".format(filename)
google.auth.exceptions.DefaultCredentialsError: File /opt/airflow/mlops-project-417704-47dfa275f621.json was not found.
[2024-03-19T07:45:44.308+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:45:44.331+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 1.062 seconds
[2024-03-19T07:46:14.510+0000] {processor.py:153} INFO - Started process (PID=2655) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:46:14.512+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:46:14.514+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:46:14.513+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:46:14.681+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:46:14.681+0000] {Convert_json_csv.py:42} INFO - Starting process in directory: /opt/airflow/data
[2024-03-19T07:46:14.682+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:46:14.681+0000] {Convert_json_csv.py:45} ERROR - Directory does not exist: /opt/airflow/data
[2024-03-19T07:46:15.667+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:46:15.660+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 13, in <module>
    from src.Merge_Files import merge_files
  File "/opt/airflow/src/Merge_Files.py", line 53, in <module>
    merge_files()
  File "/opt/airflow/src/Merge_Files.py", line 38, in merge_files
    df_merged = pd.concat(dfs, ignore_index=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 304, in concat
    sort=sort,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 351, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
[2024-03-19T07:46:15.668+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:46:15.708+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 1.206 seconds
[2024-03-19T07:46:45.751+0000] {processor.py:153} INFO - Started process (PID=2710) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:46:45.752+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:46:45.753+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:46:45.753+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:46:45.827+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:46:45.827+0000] {Convert_json_csv.py:42} INFO - Starting process in directory: /opt/airflow/data
[2024-03-19T07:46:45.828+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:46:45.828+0000] {Convert_json_csv.py:45} ERROR - Directory does not exist: /opt/airflow/data
[2024-03-19T07:46:46.331+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:46:46.325+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 13, in <module>
    from src.Merge_Files import merge_files
  File "/opt/airflow/src/Merge_Files.py", line 53, in <module>
    merge_files()
  File "/opt/airflow/src/Merge_Files.py", line 38, in merge_files
    df_merged = pd.concat(dfs, ignore_index=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 304, in concat
    sort=sort,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 351, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
[2024-03-19T07:46:46.332+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:46:46.369+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.620 seconds
[2024-03-19T07:47:16.612+0000] {processor.py:153} INFO - Started process (PID=2748) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:47:16.614+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:47:16.615+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:47:16.615+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:47:16.840+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:47:16.840+0000] {Convert_json_csv.py:42} INFO - Starting process in directory: /opt/airflow/data
[2024-03-19T07:47:16.841+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:47:16.841+0000] {Convert_json_csv.py:45} ERROR - Directory does not exist: /opt/airflow/data
[2024-03-19T07:47:17.818+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:47:17.814+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 13, in <module>
    from src.Merge_Files import merge_files
  File "/opt/airflow/src/Merge_Files.py", line 53, in <module>
    merge_files()
  File "/opt/airflow/src/Merge_Files.py", line 38, in merge_files
    df_merged = pd.concat(dfs, ignore_index=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 304, in concat
    sort=sort,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 351, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
[2024-03-19T07:47:17.819+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:47:17.865+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 1.259 seconds
[2024-03-19T07:47:48.093+0000] {processor.py:153} INFO - Started process (PID=2804) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:47:48.095+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:47:48.096+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:47:48.096+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:47:48.320+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:47:48.320+0000] {Convert_json_csv.py:42} INFO - Starting process in directory: /opt/airflow/data
[2024-03-19T07:47:48.321+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:47:48.321+0000] {Convert_json_csv.py:45} ERROR - Directory does not exist: /opt/airflow/data
[2024-03-19T07:47:49.055+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:47:49.048+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 13, in <module>
    from src.Merge_Files import merge_files
  File "/opt/airflow/src/Merge_Files.py", line 53, in <module>
    merge_files()
  File "/opt/airflow/src/Merge_Files.py", line 38, in merge_files
    df_merged = pd.concat(dfs, ignore_index=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 304, in concat
    sort=sort,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 351, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
[2024-03-19T07:47:49.056+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:47:49.095+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 1.007 seconds
[2024-03-19T07:48:19.306+0000] {processor.py:153} INFO - Started process (PID=2860) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:48:19.307+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:48:19.308+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:48:19.307+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:48:19.455+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:48:19.455+0000] {Convert_json_csv.py:42} INFO - Starting process in directory: /opt/airflow/data
[2024-03-19T07:48:19.455+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:48:19.455+0000] {Convert_json_csv.py:45} ERROR - Directory does not exist: /opt/airflow/data
[2024-03-19T07:48:20.177+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:48:20.173+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 13, in <module>
    from src.Merge_Files import merge_files
  File "/opt/airflow/src/Merge_Files.py", line 53, in <module>
    merge_files()
  File "/opt/airflow/src/Merge_Files.py", line 38, in merge_files
    df_merged = pd.concat(dfs, ignore_index=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 304, in concat
    sort=sort,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 351, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
[2024-03-19T07:48:20.178+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:48:20.212+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.910 seconds
[2024-03-19T07:48:50.435+0000] {processor.py:153} INFO - Started process (PID=2898) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:48:50.435+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:48:50.436+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:48:50.436+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:48:50.504+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:48:50.504+0000] {Convert_json_csv.py:42} INFO - Starting process in directory: /opt/airflow/data
[2024-03-19T07:48:50.504+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:48:50.504+0000] {Convert_json_csv.py:45} ERROR - Directory does not exist: /opt/airflow/data
[2024-03-19T07:48:50.974+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:48:50.971+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 13, in <module>
    from src.Merge_Files import merge_files
  File "/opt/airflow/src/Merge_Files.py", line 53, in <module>
    merge_files()
  File "/opt/airflow/src/Merge_Files.py", line 38, in merge_files
    df_merged = pd.concat(dfs, ignore_index=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 304, in concat
    sort=sort,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 351, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
[2024-03-19T07:48:50.975+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:48:50.989+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 0.557 seconds
[2024-03-19T07:49:21.186+0000] {processor.py:153} INFO - Started process (PID=2953) to work on /opt/airflow/dags/airflow.py
[2024-03-19T07:49:21.188+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-19T07:49:21.190+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:49:21.189+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-19T07:49:21.399+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:49:21.399+0000] {Convert_json_csv.py:42} INFO - Starting process in directory: /opt/airflow/data
[2024-03-19T07:49:21.400+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:49:21.399+0000] {Convert_json_csv.py:45} ERROR - Directory does not exist: /opt/airflow/data
[2024-03-19T07:49:22.175+0000] {logging_mixin.py:137} INFO - [2024-03-19T07:49:22.167+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 13, in <module>
    from src.Merge_Files import merge_files
  File "/opt/airflow/src/Merge_Files.py", line 53, in <module>
    merge_files()
  File "/opt/airflow/src/Merge_Files.py", line 38, in merge_files
    df_merged = pd.concat(dfs, ignore_index=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 304, in concat
    sort=sort,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 351, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
[2024-03-19T07:49:22.176+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-19T07:49:22.217+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/airflow.py took 1.037 seconds
